--- 
apiVersion: apps.open-cluster-management.io/v1
kind: Deployable
metadata: 
  name: redis-deployable
  labels:
    name: cm-deployable
  annotations: 
    apps.open-cluster-management.io/is-local-deployable: "false"
  namespace: default
spec: 
  placement:
    placementRef:
      kind: PlacementRule
      name: dev-pr
  template: 
    apiVersion: v1
    data: 
      database: redis
    kind: ConfigMap
    metadata: 
      name: example-cm-redis

---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: dev-pr
spec:
  clusterReplicas: 2
  clusterSelector:
    matchLabels:
      environment: Dev

