apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mcm-app
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchLabels:
      name: mcm-pak
