apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mysql-sub
  labels:
    name: mcm-pak
spec:
  channel: dev/dev-helmrepo
  name: mysql
  placement:
    placementRef:
      kind: PlacementRule
      name: mcm-pak-pr
  packageFilter:
    version: "1.6.9"
