apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: mcm-pak-pr
  namespace: default
spec:
  clusterReplicas: 3
  clusterSelector:
    matchLabels:
      environment: Dev
